name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  style:
    name: Check Code Style
    runs-on: ubuntu-22.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-8.1-composer-${{ hashFiles('composer.json') }}

      - name: Install composer packages
        run: composer install --prefer-dist --no-interaction

      - name: Check Code Style
        run: ./vendor/bin/pint --test